import time

def intro():
    print("welcome to the game")
    time.sleep(1)
    print("you win")
    time.sleep(1)
    print("or die")
    time.sleep(1)
    print("will you be eaten alive by an angry grizzly bear?")
    time.sleep(3)
    print("or jump from the 50th floor")
    time.sleep(1)
    print("to escape burning alive")
    time.sleep(1)
    print("from the explosive jet fuel")
    time.sleep(1)
    print("of the Boeing 767")
    time.sleep(1)
    print("that just slammed into the side of your office building?")
    time.sleep(5)
    print("although, if you're lucky, a quick heart attack will knock you out while you're mowing the yard...")
    time.sleep(5)
    print("less lucky, you get dementia")
    time.sleep(1)
    print("and your mind slips just enough")
    time.sleep(1)
    print("that you're not aware of yourself")
    time.sleep(1)
    print("when your body slowly stops working..")
    time.sleep(1)
    print("forcing your family to make the call ")
    time.sleep(1)
    print("whether to cut you loose ")
    time.sleep(1)
    print("or keep you strapped to tubes ")
    time.sleep(1)
    print("and tied down breathing ")
    time.sleep(1)
    print("until finally one of your organs fatally fail.")
    time.sleep(1)
    print("and they're relieved you're finally gone?")
    time.sleep(10)
    print("you know what? nevermind. welcome to the game where we all die no matter what.")
    time.sleep(3)

# def start():
#     player_name = input("Your name: ")
#     time.sleep(2)
#     answer = input("Do you want to explore? (yes/no) ")

